/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import source1.SuggestionList;
import java.awt.Color;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dilanka
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    String barcd1;
    String brand1;
    String model1;
    int qty1;
    String price1;
    String warranty1;
    int cct1;
    int pricec;
    int avqt;
    int ccqt;

    Date d1 = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel dtm;

    Color cc1 = new Color(204, 253, 244);
    Color cc2 = new Color(0, 0, 0);

    Color cc3 = new Color(0, 204, 255);
    Color cc4 = new Color(255, 255, 255);

    public Invoice() {
        initComponents();
        idgen();
        date_w.setDate(d1);
        date1.setText(sdf.format(d1));

        dtm = (DefaultTableModel) ino_tb1.getModel();
        dtm.addTableModelListener(
                new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e
            ) {
                if (e.getType() == TableModelEvent.INSERT || e.getType() == TableModelEvent.DELETE || e.getType() == TableModelEvent.UPDATE) {
                    Double tot = 0d;
                    for (int i = 0; i < ino_tb1.getRowCount(); i++) {
                        tot = tot + Double.parseDouble(ino_tb1.getValueAt(i, 6).toString());
                    }
                    Sub_total_txt.setText(String.valueOf(tot));
                }
            }

//            @Override
//            public void tableChanged(TableModelEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        brand_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        model_txt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        qty_txt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        price_txt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        date_w = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        one_r = new javax.swing.JRadioButton();
        two_r = new javax.swing.JRadioButton();
        three_r = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        yearly = new javax.swing.JRadioButton();
        custom = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Sub_total_txt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        barcode_txt = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        bardoce_com = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        payment_txt = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        balance_txt = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cost_txt = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        ava_txt = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        fname_c_txt = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lname_c_txt = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mobile_c_txt = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        mobile_c_com = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ino_tb1 = new javax.swing.JTable();
        inv_search_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        inv_search_com = new javax.swing.JComboBox<>();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        inv_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invoice Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 110, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        brand_txt.setEditable(false);
        brand_txt.setBackground(new java.awt.Color(0, 51, 51));
        brand_txt.setForeground(new java.awt.Color(255, 255, 255));
        brand_txt.setBorder(null);

        model_txt.setEditable(false);
        model_txt.setBackground(new java.awt.Color(0, 51, 51));
        model_txt.setForeground(new java.awt.Color(255, 255, 255));
        model_txt.setBorder(null);

        qty_txt.setBackground(new java.awt.Color(0, 51, 51));
        qty_txt.setForeground(new java.awt.Color(255, 255, 255));
        qty_txt.setBorder(null);
        qty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_txtActionPerformed(evt);
            }
        });
        qty_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qty_txtKeyTyped(evt);
            }
        });

        price_txt.setBackground(new java.awt.Color(0, 51, 51));
        price_txt.setForeground(new java.awt.Color(255, 255, 255));
        price_txt.setBorder(null);
        price_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                price_txtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Price");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("QTY");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Model");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Brand");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Product Id");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date_w, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date_w, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5, "card3");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setOpaque(false);

        one_r.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(one_r);
        one_r.setForeground(new java.awt.Color(255, 255, 255));
        one_r.setSelected(true);
        one_r.setText("One Year");
        one_r.setOpaque(false);

        two_r.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(two_r);
        two_r.setForeground(new java.awt.Color(255, 255, 255));
        two_r.setText("Two Year");
        two_r.setOpaque(false);

        three_r.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup2.add(three_r);
        three_r.setForeground(new java.awt.Color(255, 255, 255));
        three_r.setText("Tree Year");
        three_r.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(one_r)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(two_r)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(three_r)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one_r)
                    .addComponent(two_r)
                    .addComponent(three_r))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, "card2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Warrenty ");

        yearly.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(yearly);
        yearly.setForeground(new java.awt.Color(255, 255, 255));
        yearly.setText("Yearly");
        yearly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlyActionPerformed(evt);
            }
        });

        custom.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(custom);
        custom.setForeground(new java.awt.Color(255, 255, 255));
        custom.setSelected(true);
        custom.setText("Custom");
        custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Total Price");

        Sub_total_txt.setBackground(new java.awt.Color(0, 51, 51));
        Sub_total_txt.setForeground(new java.awt.Color(255, 255, 255));
        Sub_total_txt.setBorder(null);

        barcode_txt.setBackground(new java.awt.Color(0, 51, 51));
        barcode_txt.setForeground(new java.awt.Color(255, 255, 255));
        barcode_txt.setBorder(null);
        barcode_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcode_txtActionPerformed(evt);
            }
        });
        barcode_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcode_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                barcode_txtKeyTyped(evt);
            }
        });

        bardoce_com.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                bardoce_comPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel25.setBackground(new java.awt.Color(0, 204, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Add to table");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });

        payment_txt.setBackground(new java.awt.Color(0, 51, 51));
        payment_txt.setForeground(new java.awt.Color(255, 255, 255));
        payment_txt.setText("0.0");
        payment_txt.setBorder(null);
        payment_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payment_txtKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Payment");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Balance");

        balance_txt.setBackground(new java.awt.Color(0, 51, 51));
        balance_txt.setForeground(new java.awt.Color(255, 255, 255));
        balance_txt.setBorder(null);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/logout 03.png"))); // NOI18N
        jLabel20.setToolTipText("");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Cost");

        cost_txt.setEditable(false);
        cost_txt.setBackground(new java.awt.Color(0, 51, 51));
        cost_txt.setForeground(new java.awt.Color(255, 255, 255));
        cost_txt.setBorder(null);
        cost_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cost_txtKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Available");

        ava_txt.setEditable(false);
        ava_txt.setBackground(new java.awt.Color(0, 51, 51));
        ava_txt.setForeground(new java.awt.Color(255, 255, 255));
        ava_txt.setBorder(null);
        ava_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ava_txtActionPerformed(evt);
            }
        });
        ava_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ava_txtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearly, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(custom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ava_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bardoce_com, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(brand_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cost_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(qty_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Sub_total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(payment_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(balance_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 13, 13))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Sub_total_txt, balance_txt, barcode_txt, bardoce_com, brand_txt, cost_txt, jSeparator12, jSeparator14, jSeparator15, jSeparator16, jSeparator2, jSeparator3, jSeparator4, jSeparator5, jSeparator6, model_txt, payment_txt, price_txt, qty_txt});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(barcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bardoce_com, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brand_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ava_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(qty_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearly)
                    .addComponent(custom)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Sub_total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 600));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);

        fname_c_txt.setBackground(new java.awt.Color(0, 51, 51));
        fname_c_txt.setForeground(new java.awt.Color(255, 255, 255));
        fname_c_txt.setBorder(null);

        lname_c_txt.setBackground(new java.awt.Color(0, 51, 51));
        lname_c_txt.setForeground(new java.awt.Color(255, 255, 255));
        lname_c_txt.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Last Name");

        jLabel24.setBackground(new java.awt.Color(0, 204, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Add New Customer Or Edite");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("First Name");

        jLabel22.setBackground(new java.awt.Color(0, 204, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Clear");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 204, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Save / Print");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Mobile Number");

        mobile_c_txt.setBackground(new java.awt.Color(0, 51, 51));
        mobile_c_txt.setForeground(new java.awt.Color(255, 255, 255));
        mobile_c_txt.setBorder(null);
        mobile_c_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_c_txtActionPerformed(evt);
            }
        });
        mobile_c_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobile_c_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobile_c_txtKeyTyped(evt);
            }
        });

        mobile_c_com.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                mobile_c_comPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Date");

        date1.setBackground(new java.awt.Color(0, 51, 51));
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobile_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile_c_com, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fname_c_txt, jSeparator13, jSeparator7, jSeparator8, lname_c_txt, mobile_c_com, mobile_c_txt});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(mobile_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(mobile_c_com, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(fname_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname_c_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 650, 260));

        ino_tb1.setBackground(new java.awt.Color(0, 51, 51));
        ino_tb1.setForeground(new java.awt.Color(255, 255, 255));
        ino_tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Brand", "Model", "Warrenty", "Price", "QTY", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ino_tb1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ino_tb1.setSelectionForeground(new java.awt.Color(0, 51, 51));
        ino_tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ino_tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ino_tb1);
        if (ino_tb1.getColumnModel().getColumnCount() > 0) {
            ino_tb1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 630, 240));

        inv_search_txt.setBackground(new java.awt.Color(0, 51, 51));
        inv_search_txt.setForeground(new java.awt.Color(255, 255, 255));
        inv_search_txt.setBorder(null);
        inv_search_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_search_txtActionPerformed(evt);
            }
        });
        inv_search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inv_search_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inv_search_txtKeyTyped(evt);
            }
        });
        jPanel1.add(inv_search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 160, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Search");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 50, 20));

        inv_search_com.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                inv_search_comPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(inv_search_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Invoice");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 160, 10));

        inv_id.setEditable(false);
        inv_id.setBackground(new java.awt.Color(0, 51, 51));
        inv_id.setForeground(new java.awt.Color(255, 255, 255));
        inv_id.setBorder(null);
        jPanel1.add(inv_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 160, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yearlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlyActionPerformed

        jPanel3.removeAll();
        jPanel3.add(jPanel4);

        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_yearlyActionPerformed

    private void customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customActionPerformed
        jPanel3.removeAll();
        jPanel3.add(jPanel5);

        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_customActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Main_Menu mn = new Main_Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        New_Customer ncc = new New_Customer();
        ncc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        jLabel24.setBackground(cc1);
        jLabel24.setForeground(cc2);

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        jLabel24.setBackground(cc3);
        jLabel24.setForeground(cc4);
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        reset2();
        reset1();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered

        jLabel22.setBackground(cc1);
        jLabel22.setForeground(cc2);
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        jLabel22.setBackground(cc3);
        jLabel22.setForeground(cc4);
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        if (!(mobile_c_txt.getText().isEmpty() || fname_c_txt.getText().isEmpty() || lname_c_txt.getText().isEmpty())) {
            double ttlep = Double.parseDouble(Sub_total_txt.getText());
            double pymntp = Double.parseDouble(payment_txt.getText());
            if (pymntp >= ttlep) {
                try {
                    dtm = (DefaultTableModel) ino_tb1.getModel();
                    String prdti = null;
                    String warrnt1 = null;
                    String prict1 = null;
                    String qtyt1 = null;
                    String wwid = null;
                    String invid1 = inv_id.getText();
                    String ddd1 = date1.getText();
                    String ccci = null;
                    ResultSet rs2 = database.db.search("SELECT c_id FROM customer WHERE customer.mobile = '" + mobile_c_txt.getText() + "';");
                    if (rs2.next()) {
                        ccci = rs2.getString("c_id");

                    }
                    database.db.iud("INSERT INTO invoice (inv_id,date,custormer_c_idi) VALUES('" + invid1 + "','" + ddd1 + "','" + ccci + "')");
                    for (int p = 0; p < dtm.getRowCount(); p++) {
                        prdti = dtm.getValueAt(p, 0).toString();
                        warrnt1 = dtm.getValueAt(p, 3).toString();
                        prict1 = dtm.getValueAt(p, 4).toString();
                        qtyt1 = dtm.getValueAt(p, 5).toString();
                        database.db.iud("INSERT INTO warranty (start_date,end_date) VALUES('" + date1.getText() + "','" + warrnt1 + "')");
                        ResultSet rs1 = database.db.search("SELECT MAX(warranty.w_id) AS x FROM warranty ");
                        if (rs1.next()) {
                            wwid = rs1.getString("x");
                        }

                        database.db.iud("INSERT INTO invoice_item (selling_price,QTY,invoice_inv_id,customer_c_id,warranty_id,product_p_id) VALUES('" + prict1 + "','" + qtyt1 + "','" + invid1 + "','" + ccci + "','" + wwid + "','" + prdti + "')");

                    }
                    invcereport(invid1);

                  
                        ResultSet rs3 = database.db.search("SELECT stock.prduct_p_id,stock.qty FROM stock WHERE stock.prduct_p_id='" + prdti + "'");
                        if (rs3.next()) {
                            System.out.println("01");
                            int nqty = Integer.parseInt(qtyt1);
                            int gqty = Integer.parseInt(rs3.getString("stock.qty"));
                            if (nqty <= gqty) {
                                int sntqty = gqty - nqty;
                                System.out.println(prict1);
                                System.out.println(sntqty);
                                database.db.iud("UPDATE stock SET stock.qty = '" + sntqty + "' WHERE stock.prduct_p_id = '" + prdti + "'");
                                System.out.println("03");
                                JOptionPane.showMessageDialog(this, "Saved....!");

                            } else {
                                JOptionPane.showMessageDialog(this, "Not enough this Item");
                            }
                        }
                    

                    reset2();
                    idgen();
//                     dtm.setRowCount(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Correct Payment");
                payment_txt.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Empty Field...!");
        }


    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked

        if (!(barcode_txt.getText().isEmpty() || brand_txt.getText().isEmpty() || model_txt.getText().isEmpty() || qty_txt.getText().isEmpty() || price_txt.getText().isEmpty())) {
            barcd1 = barcode_txt.getText();
            brand1 = brand_txt.getText();
            model1 = model_txt.getText();
            qty1 = Integer.parseInt(qty_txt.getText());
            price1 = price_txt.getText();
            pricec = Integer.parseInt(price1);
            int totalc = qty1 * pricec;
            warranty1 = warrant();
            String cccc = cost_txt.getText();
            cct1 = Integer.parseInt(cccc);
            avqt = Integer.parseInt(ava_txt.getText());
            ccqt = Integer.parseInt(qty_txt.getText());
            if (avqt < ccqt) {
                JOptionPane.showMessageDialog(this, "check QTY");
                qty_txt.grabFocus();
            } else {
                if (pricec < cct1) {
                    System.out.println("");
                    JOptionPane.showMessageDialog(this, "check price");
                    price_txt.grabFocus();

                } else {

                    DefaultTableModel dtm = (DefaultTableModel) ino_tb1.getModel();
                    Object[] row = {barcd1, brand1, model1, warranty1, price1, qty1, totalc};
//        dtm.setRowCount(0);
                    dtm.addRow(row);
                    reset1();
                    barcode_txt.grabFocus();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Empty Field... Please Check Befor Add to Table....!");
        }


    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        jLabel25.setBackground(cc1);
        jLabel25.setForeground(cc2);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        jLabel25.setBackground(cc3);
        jLabel25.setForeground(cc4);
    }//GEN-LAST:event_jLabel25MouseExited

    private void barcode_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcode_txtKeyReleased

        SuggestionList.showList(barcode_txt, bardoce_com, "SELECT p_id FROM product WHERE p_id LIKE '" + barcode_txt.getText() + "%'", "p_id", evt, this.getClass().getName());
    }//GEN-LAST:event_barcode_txtKeyReleased

    private void barcode_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcode_txtActionPerformed

//        try {
//          barcd1 = barcode_txt.getText();
//            ResultSet rs = database.db.search("SELECT * FROM product WHERE p_id = '"+barcd1+"' ");
//            if(rs.next()){
//            brand_txt.setText(rs.getString("brand"));
//            model_txt.setText(rs.getString("model"));
//            
//            }
//        } catch (Exception e) {
//        }
//       if(barcode_txt.getText()==null){
//       
//       }else{
//        qty_txt.grabFocus();
//       }
    }//GEN-LAST:event_barcode_txtActionPerformed

    private void ino_tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ino_tb1MouseClicked
        if (evt.getClickCount() == 2) {
            DefaultTableModel dtm = (DefaultTableModel) ino_tb1.getModel();
            int tr = JOptionPane.showConfirmDialog(this, "Are you sure remove this row..", "confirm", JOptionPane.YES_NO_OPTION);
            if (tr == JOptionPane.YES_OPTION) {

                dtm.removeRow(ino_tb1.getSelectedRow());

            }
        }
    }//GEN-LAST:event_ino_tb1MouseClicked

    private void qty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_txtActionPerformed
        price_txt.grabFocus();
    }//GEN-LAST:event_qty_txtActionPerformed

    private void barcode_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcode_txtKeyTyped
        barcd1 = barcode_txt.getText();
        dtm = (DefaultTableModel) ino_tb1.getModel();
        String tbar1 = null;
        for (int j = 0; j < dtm.getRowCount(); j++) {
            tbar1 = dtm.getValueAt(j, 0).toString();

        }
        if (barcd1.equals(tbar1)) {
            barcode_txt.setText(null);
            barcode_txt.grabFocus();
        } else {
            try {
                barcd1 = barcode_txt.getText();
                ResultSet rs = database.db.search("SELECT * FROM product WHERE p_id = '" + barcd1 + "' ");
                if (rs.next()) {
                    brand_txt.setText(rs.getString("brand"));
                    model_txt.setText(rs.getString("model"));
                    qty_txt.grabFocus();

                }
                ResultSet rs0 = database.db.search("SELECT stock.qty FROM stock WHERE stock.prduct_p_id = '" + barcd1 + "'");
                if (rs0.next()) {
                    ava_txt.setText(rs0.getString("stock.qty"));
                }
                ResultSet rs2 = database.db.search("SELECT grn_item.buying_price FROM grn_item WHERE grn_item.product_p_id = '" + barcd1 + "'");
                if (rs2.next()) {
                    cost_txt.setText(rs2.getString("grn_item.buying_price"));
                }
            } catch (Exception e) {
            }
//            if (barcode_txt.getText().length() >= 3) {
//                qty_txt.grabFocus();
//
//            }
//       if(barcode_txt.getText()==null){
//       
//       }else{
//        qty_txt.grabFocus();
//       }
        }
    }//GEN-LAST:event_barcode_txtKeyTyped

    private void mobile_c_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_c_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_c_txtActionPerformed

    private void mobile_c_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobile_c_txtKeyReleased
        SuggestionList.showList(mobile_c_txt, mobile_c_com, "SELECT customer.mobile FROM customer WHERE customer.mobile LIKE '" + mobile_c_txt.getText() + "%'", "customer.mobile", evt, this.getClass().getName());        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_c_txtKeyReleased

    private void mobile_c_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobile_c_txtKeyTyped

        try {

            String mobilec = mobile_c_txt.getText();
            ResultSet rs = database.db.search("SELECT * FROM customer WHERE customer.mobile = '" + mobilec + "'");
            if (rs.next()) {
                fname_c_txt.setText(rs.getString("f_name"));
                lname_c_txt.setText(rs.getString("l_name"));

            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_mobile_c_txtKeyTyped

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        jLabel17.setBackground(cc1);
        jLabel17.setForeground(cc2);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        jLabel17.setBackground(cc3);
        jLabel17.setForeground(cc4);
    }//GEN-LAST:event_jLabel17MouseExited

    private void qty_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty_txtKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();

        }


    }//GEN-LAST:event_qty_txtKeyTyped

    private void price_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_txtKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_price_txtKeyTyped

    private void inv_search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inv_search_txtKeyReleased
        SuggestionList.showList(inv_search_txt, inv_search_com, "SELECT invoice_item.invoice_inv_id FROM invoice_item WHERE invoice_item.invoice_inv_id LIKE '" + inv_search_txt.getText() + "%'", "invoice_item.invoice_inv_id", evt, this.getClass().getName());
    }//GEN-LAST:event_inv_search_txtKeyReleased

    private void inv_search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inv_search_txtActionPerformed

    private void inv_search_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inv_search_txtKeyTyped
        try {
            String invid2 = inv_search_txt.getText();
            ResultSet rs = database.db.search("SELECT invoice_item.selling_price,invoice_item.QTY,product.p_id, product.brand,product.model,warranty.end_date FROM invoice_item INNER JOIN product ON invoice_item.product_p_id = product.p_id JOIN warranty ON invoice_item.warranty_id = warranty.w_id WHERE invoice_item.invoice_inv_id = '" + invid2 + "'");
            String pidt = null;
            String brdnt = null;
            String mdlt = null;
            String wrrnt = null;
            int prcet = 0;
            int qtyt = 0;
            while (rs.next()) {
                pidt = rs.getString("product.p_id");
                brdnt = rs.getString("product.brand");
                mdlt = rs.getString("product.model");
                wrrnt = rs.getString("warranty.end_date");
                prcet = Integer.parseInt(rs.getString("invoice_item.selling_price"));
                qtyt = Integer.parseInt(rs.getString("invoice_item.QTY"));
                int totalt = prcet * qtyt;

                DefaultTableModel dtm = (DefaultTableModel) ino_tb1.getModel();

                Object[] row1 = {pidt, brdnt, mdlt, wrrnt, prcet, qtyt, totalt};
                dtm.setRowCount(0);
                dtm.addRow(row1);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_inv_search_txtKeyTyped

    private void payment_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payment_txtKeyTyped
        double subtt = Double.parseDouble(Sub_total_txt.getText());
        double pymt = Double.parseDouble(payment_txt.getText());

        double blncet = subtt - pymt;
        String blncs = String.valueOf(blncet);
        balance_txt.setText(blncs);
    }//GEN-LAST:event_payment_txtKeyTyped

    private void inv_search_comPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_inv_search_comPopupMenuWillBecomeInvisible
        SuggestionList.setSelectedItem(inv_search_txt, inv_search_com);
    }//GEN-LAST:event_inv_search_comPopupMenuWillBecomeInvisible

    private void mobile_c_comPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_mobile_c_comPopupMenuWillBecomeInvisible
        SuggestionList.setSelectedItem(mobile_c_txt, mobile_c_com);
    }//GEN-LAST:event_mobile_c_comPopupMenuWillBecomeInvisible

    private void bardoce_comPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_bardoce_comPopupMenuWillBecomeInvisible
        SuggestionList.setSelectedItem(barcode_txt, bardoce_com);
    }//GEN-LAST:event_bardoce_comPopupMenuWillBecomeInvisible

    private void cost_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cost_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cost_txtKeyTyped

    private void ava_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ava_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ava_txtActionPerformed

    private void ava_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ava_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ava_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Sub_total_txt;
    private javax.swing.JTextField ava_txt;
    private javax.swing.JTextField balance_txt;
    private javax.swing.JTextField barcode_txt;
    private javax.swing.JComboBox<String> bardoce_com;
    private javax.swing.JTextField brand_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cost_txt;
    private javax.swing.JRadioButton custom;
    private javax.swing.JTextField date1;
    private com.toedter.calendar.JDateChooser date_w;
    private javax.swing.JTextField fname_c_txt;
    private javax.swing.JTable ino_tb1;
    private javax.swing.JTextField inv_id;
    private javax.swing.JComboBox<String> inv_search_com;
    private javax.swing.JTextField inv_search_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lname_c_txt;
    private javax.swing.JComboBox<String> mobile_c_com;
    private javax.swing.JTextField mobile_c_txt;
    private javax.swing.JTextField model_txt;
    private javax.swing.JRadioButton one_r;
    private javax.swing.JTextField payment_txt;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField qty_txt;
    private javax.swing.JRadioButton three_r;
    private javax.swing.JRadioButton two_r;
    private javax.swing.JRadioButton yearly;
    // End of variables declaration//GEN-END:variables
String warrant() {
        String timep = "";
        if (yearly.isSelected()) {
            if (one_r.isSelected()) {
                timep = "One Year";

            } else if (two_r.isSelected()) {
                timep = "Two Years";
            } else {
                timep = "Tree Years";
            }
        } else {
            String yd1 = sdf.format(date_w.getDate());
            timep = yd1;
        }
        return timep;
    }

    void reset1() {
        barcode_txt.setText(null);
        brand_txt.setText(null);
        model_txt.setText(null);
        qty_txt.setText(null);
        price_txt.setText(null);
        cost_txt.setText(null);
        ava_txt.setText(null);

    }

    void reset2() {
        mobile_c_txt.setText(null);
        fname_c_txt.setText(null);
        lname_c_txt.setText(null);
        Sub_total_txt.setText(null);
        payment_txt.setText("0.0");
        dtm = (DefaultTableModel) ino_tb1.getModel();
        dtm.setRowCount(0);

    }

    void idgen() {
        try {
            ResultSet rs1 = database.db.search("SELECT COUNT(inv_id) AS x FROM invoice");
            if (rs1.next()) {
                int x = Integer.parseInt(rs1.getString("x"));
                x++;
                inv_id.setText("INV00" + x);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void invcereport(String invdd) {
        try {

            Map<String, Object> parameter = new HashMap<>();
            parameter.put("INVID", invdd);

            InputStream jr = GRN.class.getResourceAsStream("/BILL1/invoice_mobile.jasper");

            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, database.db.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
