/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author Dilanka
 */
public class Lock_state extends javax.swing.JFrame {

    /**
     * Creates new form Lock_state
     */
    int val;

    public Lock_state() {
        initComponents();
        setCountDown();
        countDown();
        fp_btn.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fp_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/ezgif.com-resize new22.gif"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/logout 03.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        time.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        time.setForeground(new java.awt.Color(204, 0, 0));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("15");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Waiting for Re enter.....!");

        fp_btn.setBackground(new java.awt.Color(0, 51, 51));
        fp_btn.setForeground(new java.awt.Color(255, 255, 255));
        fp_btn.setText("Forgot Password");
        fp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fp_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fp_btn))
                        .addGap(41, 41, 41)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fp_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
        
    }//GEN-LAST:event_formWindowActivated

    private void fp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fp_btnActionPerformed
       new Forgot_password().setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_fp_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lock_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lock_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lock_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lock_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lock_state().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fp_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
private void countDown() {
        Thread thread;

        thread = new Thread() {
            @Override
            public void run() {

                int tim = Integer.parseInt(time.getText());
                for (int i = 0; i < tim; i++) {

                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    time.setText(Integer.parseInt(time.getText()) - 1 + "");
                    writeCurrentTimeToFile();

                }
                disp();
//                new Login().setVisible(true);

            }

            private void writeCurrentTimeToFile() {

                try {
                    File folder = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile");
                    File folder2 = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details");
                    File file = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details\\countdn.dat");
                    if (!(folder.exists())) {
                        folder.mkdir();
                    }
                    if (!(folder2.exists())) {
                        folder2.mkdir();
                    }

                    file.setWritable(true);
                    if (file.exists()) {
                        file.delete();

                    }
                    FileWriter fr = new FileWriter(file);

                    BufferedWriter br = new BufferedWriter(fr);

                    br.write(String.valueOf(time.getText()));
                    file.setWritable(false);
                    br.close();
                    fr.close();
                } catch (Exception e) {
                    e.printStackTrace();

                }
            }
        };
        thread.start();
    }

    private void setCountDown() {
        try {
            File file = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details\\countdn.dat");

            BufferedReader br = new BufferedReader(new FileReader(file));

            String st = br.readLine();
            time.setText(st);

            br.close();

        } catch (Exception e) {
        }

    }

    private void disp() {
        writeToCountDownFile();
        writeToAttemptFile();
//        this.dispose();
//        new NewJFrame().setVisible(true);
fp_btn.setEnabled(true);
    }

    private void writeToCountDownFile() {
        if (val == 0) {

            try {
                File folder = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile");
                File folder2 = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details");
                File file = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details\\countdn.dat");
                if (!(folder.exists())) {
                    folder.mkdir();
                }
                if (!(folder2.exists())) {
                    folder2.mkdir();
                }

                file.setWritable(true);
                if (file.exists()) {
                    file.delete();

                }
                FileWriter fr = new FileWriter(file);

                BufferedWriter br = new BufferedWriter(fr);

                br.write(String.valueOf(15));
                file.setWritable(false);
                br.close();
                fr.close();
            } catch (Exception e) {
                e.printStackTrace();

            }
        }
    }

    private void writeToAttemptFile() {
        try {
            File folder = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile");
            File folder2 = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details");
            File file = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details\\atmpt.dat");
            if (!(folder.exists())) {
                folder.mkdir();
            }
            if (!(folder2.exists())) {
                folder2.mkdir();
            }
            file.setWritable(true);
            if (file.exists()) {
                file.delete();

            }
            FileWriter fr = new FileWriter(file);

            BufferedWriter br = new BufferedWriter(fr);

            br.write(String.valueOf(1));
            file.setWritable(false);
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();

        }
    }

}
