/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilanka
 */
public class Loginn extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String un;
    String pw;
    String type1;
    static String type;
    int val;
    Color cc1 = new Color(204, 253, 244);
    Color cc2 = new Color(0, 0, 0);

    Color cc3 = new Color(0, 204, 204);
    Color cc4 = new Color(255, 255, 255);

    public Loginn() {
        initComponents();

        uname.setText(null);
        pw_txt.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pw_txt = new javax.swing.JPasswordField();
        cancelbtn = new javax.swing.JLabel();
        Loginbtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(482, 259));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        uname.setBackground(new java.awt.Color(0, 51, 51));
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText(" ");
        uname.setBorder(null);
        uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unameMouseEntered(evt);
            }
        });
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        pw_txt.setBackground(new java.awt.Color(0, 51, 51));
        pw_txt.setForeground(new java.awt.Color(255, 255, 255));
        pw_txt.setBorder(null);
        pw_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pw_txtMouseEntered(evt);
            }
        });
        pw_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw_txtActionPerformed(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(0, 204, 204));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbtn.setText("   Cancel");
        cancelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelbtn.setOpaque(true);
        cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelbtnMouseExited(evt);
            }
        });

        Loginbtn.setBackground(new java.awt.Color(0, 204, 204));
        Loginbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("     Login");
        Loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loginbtn.setOpaque(true);
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginbtnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");

        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Forgot Password....!");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/logout 03.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pw_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pw_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/logo22.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Grand Mobile Shop");
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        pw_txt.grabFocus();
    }//GEN-LAST:event_unameActionPerformed

    private void pw_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw_txtActionPerformed
        Loginbtn.grabFocus();
    }//GEN-LAST:event_pw_txtActionPerformed

    private void cancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelbtnMouseClicked
    int attempt_count = 0;
    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked

        un = uname.getText();
        pw = pw_txt.getText();

        /* if (un_txt.getText().isEmpty() && pw_txt.getText().isEmpty()) {
    
            JOptionPane.showConfirmDialog(this, "Please Enter Your Password and Username....!");
        } else {
            if (un_txt.getText().length() >= 4 && pw_txt.getText().length() >= 4) {
                if (un_txt.getText().length() <= 15 && pw_txt.getText().length() <= 15) {
                    if(un_txt.getText().equals(pw_txt.getText())){
                        JOptionPane.showConfirmDialog(this, "Please Enter Different Username And Password ");
                    }else{
                        try {
                        un = un_txt.getText();
                        pw = pw_txt.getText();
                        type1 =String.valueOf(jComboBox1.getSelectedItem());
                        String qry = "SELECT * FROM login WHERE username='"+un+"' and password='"+pw+"' and type='"+type1+"'";
                        ResultSet rs = database.db.search(qry);
                        if(rs.next()){
                            
                            System.out.println("fc");
                            
                            if(un.equalsIgnoreCase(rs.getString("username")) && pw.equalsIgnoreCase(rs.getString("password"))){
                        Main_Menu mn = new Main_Menu();System.out.println("gn");
                        mn.setVisible(true);
                        this.dispose();}else{System.out.println("jop");
                            JOptionPane.showConfirmDialog(this, "Your Password or Username is Incorrect...!");
                            }
                        }
                            
                        } catch (Exception e) {e.printStackTrace();
                        }
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Maximum 15 charactors only ");
                }

            } else {
                JOptionPane.showConfirmDialog(this, "Please Enter Minimum 4 Character ");

            }

        }*/
//        Main_Menu mm = new Main_Menu();
//        mm.setVisible(true);
//        this.dispose();
        boolean unisemp = un.isEmpty();
        boolean pwisemp = pw.isEmpty();
        if (unisemp || pwisemp) {
            JOptionPane.showMessageDialog(this, "User Name Or Password Is Empty...!", "Empty Field", JOptionPane.ERROR_MESSAGE);
            uname.setText(null);
            pw_txt.setText(null);
            attempt_count++;
            logger.Logger.writeLogger("undefind", "undefind", "Fail", attempt_count);
            if (attempt_count > 3) {
                new Lock_state().setVisible(true);
                this.dispose();
                attempt_count = 0;
            }
            if (unisemp) {
                uname.grabFocus();
            } else {
                pw_txt.grabFocus();
            }

        } else {
            int uleng = un.length();
            int pleng = pw.length();
            if (uleng >= 4 || pleng >= 4) {
                if (uleng <= 15 || pleng <= 15) {

                    try {

//                        String qry = "SELECT * FROM users WHERE username='" + un + "' and password='" + pw + "'";
                        String qry = "SELECT * FROM users WHERE users.username='" + Cryptography.Cryption.encript(un) + "'";
                        ResultSet rs = database.db.search(qry);

                        if (rs.next()) {
                            String decriptun = Cryptography.Cryption.decript(rs.getString("username"));
                            String decriptpw = Cryptography.Cryption.decript(rs.getString("password"));
                            System.out.println(decriptun);
                            System.out.println(decriptpw);
                            if (un.equals(decriptun) && pw.equals(decriptpw)) {
                                logger.Logger.writeLogger(decriptun, "undefind", "Succes", attempt_count);

                                System.out.println("0222");
                                Main_Menu mn = new Main_Menu();
                                mn.setVisible(true);
                                this.dispose();
                            } else {
//                                System.out.println("0111");
                                JOptionPane.showMessageDialog(this, "Your Password or Username is Incorrect...!", "Incorrect Entry", JOptionPane.ERROR_MESSAGE);
                                uname.setText(null);
                                pw_txt.setText(null);
                                attempt_count++;
                                logger.Logger.writeLogger("undefind", "undefind", "Fail", attempt_count);
                                if (attempt_count > 3) {
                                    new Lock_state().setVisible(true);
                                    this.dispose();
                                    attempt_count = 0;
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Your Password or Username is Incorrect...!", "Incorrect Entry", JOptionPane.ERROR_MESSAGE);
                            attempt_count++;
                            logger.Logger.writeLogger("undefind", "undefind", "Fail", attempt_count);
                            if (attempt_count > 3) {
                                new Lock_state().setVisible(true);
                                this.dispose();
                                attempt_count = 0;
                            }
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                } else {

                    JOptionPane.showMessageDialog(this, "Please Enter Your User Name Or Password  Maximum 15 characters ...!", "check Character Lengh", JOptionPane.ERROR_MESSAGE);
                    uname.setText(null);
                    pw_txt.setText(null);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Your User Name Or Password minimum 4 characters...! ", "check Character Lengh", JOptionPane.ERROR_MESSAGE);
                uname.setText(null);
                pw_txt.setText(null);

            }
        }

    }//GEN-LAST:event_LoginbtnMouseClicked

    private void unameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMouseEntered
        uname.setToolTipText("Please Enter Your UserName");
    }//GEN-LAST:event_unameMouseEntered

    private void pw_txtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pw_txtMouseEntered
        pw_txt.setToolTipText("Please Enter Your Password");
    }//GEN-LAST:event_pw_txtMouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Forgot_password frg = new Forgot_password();
        frg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        Color cc1 = new Color(0, 0, 0);
        Color cc2 = new Color(255, 255, 255);

        jLabel15.setBackground(cc1);
        jLabel15.setForeground(cc2);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        Color cc3 = new Color(0, 0, 204);
        Color cc4 = new Color(153, 255, 255);

        jLabel15.setBackground(cc3);
        jLabel15.setForeground(cc4);
    }//GEN-LAST:event_jLabel15MouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        setTimer();
    }//GEN-LAST:event_formWindowActivated

    private void LoginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseEntered
        Loginbtn.setBackground(cc1);
        Loginbtn.setForeground(cc2);

        // TODO add your handling code here:
    }//GEN-LAST:event_LoginbtnMouseEntered

    private void LoginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseExited
        Loginbtn.setBackground(cc3);
        Loginbtn.setForeground(cc4);

        // TODO add your handling code here:
    }//GEN-LAST:event_LoginbtnMouseExited

    private void cancelbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseEntered
        cancelbtn.setBackground(cc1);
        cancelbtn.setForeground(cc2);


    }//GEN-LAST:event_cancelbtnMouseEntered

    private void cancelbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseExited
        cancelbtn.setBackground(cc3);
        cancelbtn.setForeground(cc4);
// TODO add your handling code here:
    }//GEN-LAST:event_cancelbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loginbtn;
    private javax.swing.JLabel cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pw_txt;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
 void setTimer() {
        try {
            File file = new File(System.getenv("PROGRAMDATA") + "\\Login System Mobile\\Login Details\\countdn.dat");
            if (!(file.exists())) {
                file.mkdir();
            }

            BufferedReader br = new BufferedReader(new FileReader(file));

            String st = br.readLine();
            int st1 = Integer.parseInt(st);
            if (st1 == 15) {

            } else {
                System.out.println(st1);
                Lock_state lkl = new Lock_state();
                lkl.setVisible(true);
                this.dispose();
            }

            br.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
